### ISSUE TITLE
14.0.2 sometimes fails to play media in Home Assistant

### ISSUE THREAD

**Issue by bdraco** [home-assistant-libs/pychromecast#964]
https://github.com/home-assistant/core/pull/127555

Tried to reproduce with 
```
action: media_player.play_media
data:
  media_content_id: >-
    https://file-examples.com/storage/fe36b23e6a66fc0679c1f86/2017/11/file_example_MP3_1MG.mp3
  media_content_type: music
target:
  entity_id: media_player.living_room_tv
```

Can repro with debug off for `pychromecast` after 8-10 attempts.  With debug logging turned on I cannot reproduce so its some type of race
